[New RM] DuckDuckGo
stanford-oval/storm pull request #145
Opened 2024-08-17 15:40 UTC by zenith110

This PR aims to accomplish the following:

- Creates a retriever model using DuckDuckGo api utilizing the [duckduckgo_search](https://github.com/deedy5/duckduckgo_search) library.
- Update all the LM examples to include DuckDuckGo as a retriever in examples/
- Added documentation for new RM, as well as custom options to enable safe search/language.

Input for this example was pokemon.

Output results are below:
```
python examples/run_storm_wiki_gpt.py --output-dir ./output/ddg --retriever duckduckgo --do-research --do-generate-outline --do-generate-article --do-polish-article
primp : INFO     : response: https://duckduckgo.com/ 200 17851
primp : INFO     : response: https://duckduckgo.com/ 200 17826
primp : INFO     : response: https://duckduckgo.com/ 200 18008
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pok%C3%A9mon+popularity+worldwide&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-129249434834354548125976907575122126238&bing_market=wt-WT&ex=-1 200 28905
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=History+of+Pokemon+franchise&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-215688423644065080573760632631242516542&bing_market=wt-WT&ex=-1 200 34438
primp : INFO     : response: https://duckduckgo.com/ 200 18000
primp : INFO     : response: https://duckduckgo.com/ 200 17891
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pokemon+breeding+mechanics+in+generation+3&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-158056105470667184619806054620694982411&bing_market=wt-WT&ex=-1 200 46564
primp : INFO     : response: https://duckduckgo.com/ 200 18008
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pok%C3%A9mon+influence+in+different+cultures&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-190062255219678873094355623798618716733&bing_market=wt-WT&ex=-1 200 37121
primp : INFO     : response: https://duckduckgo.com/ 200 17967
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Key+elements+of+Pokemon+franchise&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-19184000702775355516285330326832236310&bing_market=wt-WT&ex=-1 200 35565
primp : INFO     : response: https://duckduckgo.com/ 200 17957
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pokemon+breeding+mechanics+in+generation+1&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-191662332061853487589854932556394924935&bing_market=wt-WT&ex=-1 200 47366
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pok%C3%A9mon+cultural+impact+by+country&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-332933843419043581125777214343629805443&bing_market=wt-WT&ex=-1 200 26442
primp : INFO     : response: https://duckduckgo.com/ 200 18004
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=General+overview+of+Pokemon+franchise&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-43051092562758489970523555587206032225&bing_market=wt-WT&ex=-1 200 31259
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pokemon+breeding+mechanics+in+generation+2&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-98597388395079432292487389899060676967&bing_market=wt-WT&ex=-1 200 46458
primp : INFO     : response: https://duckduckgo.com/ 200 18240
primp : INFO     : response: https://duckduckgo.com/ 200 17996
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pok%C3%A9mon+cultural+significance+in+different+countries&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-302455654261892553942620478108956667310&bing_market=wt-WT&ex=-1 200 24591
primp : INFO     : response: https://duckduckgo.com/ 200 18550
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Evolution+of+Pokemon+in+popular+culture&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-231683652380273937004558031336891212322&bing_market=wt-WT&ex=-1 200 29333
primp : INFO     : response: https://duckduckgo.com/ 200 17946
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Impact+of+international+expansion+of+Pok%C3%A9mon+on+cultural+significance&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-11200684812693598321046570499075236720&bing_market=wt-WT&ex=-1 200 23247
primp : INFO     : response: https://duckduckgo.com/ 200 18228
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pokemon+franchise+influence+on+society&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-92532925074780844166694809854872994820&bing_market=wt-WT&ex=-1 200 24826
primp : INFO     : response: https://duckduckgo.com/ 200 18150
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Introduction+of+new+Pok%C3%A9mon+in+later+generations&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-213651897599102835988391789128957127802&bing_market=wt-WT&ex=-1 200 27333
primp : INFO     : response: https://duckduckgo.com/ 200 18463
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Impact+of+Pokemon+franchise+on+popular+culture&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-184982165892032937003043399095966858452&bing_market=wt-WT&ex=-1 200 25008
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Improvements+in+breeding+mechanics+of+Pok%C3%A9mon+in+Generation+6&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-263900224743465678794443065316720644902&bing_market=wt-WT&ex=-1 200 35487
primp : INFO     : response: https://duckduckgo.com/ 200 18554
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Changes+in+breeding+mechanics+of+Pok%C3%A9mon+from+Generation+6+onwards&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-13009221313963447274061041979850108320&bing_market=wt-WT&ex=-1 200 35167
primp : INFO     : response: https://duckduckgo.com/ 200 18508
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Comparison+of+breeding+mechanics+in+different+Pok%C3%A9mon+generations&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-45837180021057475472832486922139535494&bing_market=wt-WT&ex=-1 200 36649
primp : INFO     : response: https://duckduckgo.com/ 200 18198
primp : INFO     : response: https://duckduckgo.com/ 200 18808
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pokemon+characters+contribution+to+franchise+success&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-35387584357503951149786457497573218182&bing_market=wt-WT&ex=-1 200 21981
primp : INFO     : response: https://duckduckgo.com/ 200 18169
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Impact+of+Generation+3+Pok%C3%A9mon+on+cultural+significance+in+different+countries&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-277301478597205438538401168802403074254&bing_market=wt-WT&ex=-1 200 23680
primp : INFO     : response: https://duckduckgo.com/ 200 18288
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Popular+Pokemon+characters+in+Pokemon+franchise&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-274034312682286756031617244841971097318&bing_market=wt-WT&ex=-1 200 43394
primp : INFO     : response: https://duckduckgo.com/ 200 18030
primp : INFO     : response: https://duckduckgo.com/ 200 18169
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Cultural+significance+of+Pok%C3%A9mon+in+different+countries&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-311683773483935830606258027745036181806&bing_market=wt-WT&ex=-1 200 37318
primp : INFO     : response: https://duckduckgo.com/ 200 18770
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Most+iconic+and+popular+Pokemon+characters&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-278325000143127116537133211417368449504&bing_market=wt-WT&ex=-1 200 43819
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Pokemon+breeding+mechanics+evolution+Generation+6&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-102296155810643392695964731955234839610&bing_market=wt-WT&ex=-1 200 47028
primp : INFO     : response: https://duckduckgo.com/ 200 18316
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Impact+of+Generation+5+Pok%C3%A9mon+on+cultural+significance+in+different+countries&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-247879090801879403307551725275674782038&bing_market=wt-WT&ex=-1 200 23474
primp : INFO     : response: https://links.duckduckgo.com/d.js?q=Breeding+changes+in+Pokemon+games+Generation+6+and+beyond&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-302292130 [...]

2024-08-19 06:38 UTC, shaoyijia requested changes
Thanks for providing the log! It's pretty helpful. Just a few nits and I am happy to merge this.

2024-08-19 06:38 UTC, shaoyijia commented on knowledge_storm/rm.py
> +from duckduckgo_search import DDGS
Could we move this to `DuckDuckGoSearchRM.__init__()`? In this way, people don't necessarily need to install this package and we don't need to change `requirements.txt`.  You can do something similar to [here](https://github.com/stanford-oval/storm/blob/53b7f1ece52c1315694bb16e689e69a654332768/knowledge_storm/lm.py#L247)

2024-08-19 06:38 UTC, shaoyijia commented on knowledge_storm/rm.py
> +    # Store usage of credits and reset the class usage variable
Delete this line.

2024-08-19 06:38 UTC, shaoyijia commented on knowledge_storm/rm.py
> +
Add one more line break here.

2024-08-19 06:38 UTC, shaoyijia commented on knowledge_storm/rm.py
> +    # this is the important function that is used by Retriever in the pipeline
Delete this line.

2024-08-19 23:55 UTC, Yucheng-Jiang commented
Thanks for resolving the comments! Just one additional nit, otherwise looks good to me.

Would you please add DuckDuckGo in [readme API section here](https://github.com/stanford-oval/storm?tab=readme-ov-file#api)?

<img width="1328" alt="Screenshot 2024-08-20 at 7 55 16 AM" src="https://github.com/user-attachments/assets/cc42106a-363b-430f-9f82-8dd0bed243cb">

2024-08-23 04:08 UTC, shaoyijia submitted a review, later dismissed
Thanks!

2024-08-23 04:09 UTC, shaoyijia approved these changes

2024-08-23 04:09 UTC, merged